// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwmPlimMuH5bV7BUP3qYQV1wN4WwI1o-s',
    appId: '1:884568768150:web:7520f3ee4a38eaa35dccb7',
    messagingSenderId: '884568768150',
    projectId: 'tiktok-clone-backend-hjkim',
    authDomain: 'tiktok-clone-backend-hjkim.firebaseapp.com',
    storageBucket: 'tiktok-clone-backend-hjkim.appspot.com',
    measurementId: 'G-PW3VPPEGP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZN_3haZNoMvpnPHuUrthnsM0YwcdYj4',
    appId: '1:884568768150:android:bd70d67e00cbc2325dccb7',
    messagingSenderId: '884568768150',
    projectId: 'tiktok-clone-backend-hjkim',
    storageBucket: 'tiktok-clone-backend-hjkim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBtdXinT3IXS4-BjA_Gw53JEJmMXd19js',
    appId: '1:884568768150:ios:2db007c28b9bdea95dccb7',
    messagingSenderId: '884568768150',
    projectId: 'tiktok-clone-backend-hjkim',
    storageBucket: 'tiktok-clone-backend-hjkim.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

}